### ISSUE TITLE
GNOME 45 port

### ISSUE THREAD

**Issue by iadegesso** [kevinhwang91/gnome-shell-ibus-switcher#1]
Are you planning the port to GNOME 45?

Thanks

Iade

**Comment by kevinhwang91** [comment]
Today

**Comment by kevinhwang91** [comment]
Sorry, archlinux gnome-shell version is still 44.5, need to wait for it to upgrade to 45.

**Comment by ArcanusNEO** [comment]
Arch Linux just got GNOME 45 released to stable. Could you update the G45 version?

Thanks
